// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guestbook.proto

package com.guestbookfe.model;

public final class GuestProto {
  private GuestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GuestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:guestbook.Guest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string institution = 2;</code>
     * @return The institution.
     */
    java.lang.String getInstitution();
    /**
     * <code>string institution = 2;</code>
     * @return The bytes for institution.
     */
    com.google.protobuf.ByteString
        getInstitutionBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code guestbook.Guest}
   */
  public static final class Guest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:guestbook.Guest)
      GuestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Guest.newBuilder() to construct.
    private Guest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Guest() {
      name_ = "";
      institution_ = "";
      email_ = "";
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Guest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Guest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              institution_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guestbookfe.model.GuestProto.Guest.class, com.guestbookfe.model.GuestProto.Guest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTITUTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object institution_;
    /**
     * <code>string institution = 2;</code>
     * @return The institution.
     */
    @java.lang.Override
    public java.lang.String getInstitution() {
      java.lang.Object ref = institution_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        institution_ = s;
        return s;
      }
    }
    /**
     * <code>string institution = 2;</code>
     * @return The bytes for institution.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstitutionBytes() {
      java.lang.Object ref = institution_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        institution_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getInstitutionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, institution_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getInstitutionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, institution_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guestbookfe.model.GuestProto.Guest)) {
        return super.equals(obj);
      }
      com.guestbookfe.model.GuestProto.Guest other = (com.guestbookfe.model.GuestProto.Guest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getInstitution()
          .equals(other.getInstitution())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + INSTITUTION_FIELD_NUMBER;
      hash = (53 * hash) + getInstitution().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guestbookfe.model.GuestProto.Guest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guestbookfe.model.GuestProto.Guest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code guestbook.Guest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:guestbook.Guest)
        com.guestbookfe.model.GuestProto.GuestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guestbookfe.model.GuestProto.Guest.class, com.guestbookfe.model.GuestProto.Guest.Builder.class);
      }

      // Construct using com.guestbookfe.model.GuestProto.Guest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        institution_ = "";

        email_ = "";

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guest_descriptor;
      }

      @java.lang.Override
      public com.guestbookfe.model.GuestProto.Guest getDefaultInstanceForType() {
        return com.guestbookfe.model.GuestProto.Guest.getDefaultInstance();
      }

      @java.lang.Override
      public com.guestbookfe.model.GuestProto.Guest build() {
        com.guestbookfe.model.GuestProto.Guest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.guestbookfe.model.GuestProto.Guest buildPartial() {
        com.guestbookfe.model.GuestProto.Guest result = new com.guestbookfe.model.GuestProto.Guest(this);
        result.name_ = name_;
        result.institution_ = institution_;
        result.email_ = email_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guestbookfe.model.GuestProto.Guest) {
          return mergeFrom((com.guestbookfe.model.GuestProto.Guest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guestbookfe.model.GuestProto.Guest other) {
        if (other == com.guestbookfe.model.GuestProto.Guest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getInstitution().isEmpty()) {
          institution_ = other.institution_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guestbookfe.model.GuestProto.Guest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guestbookfe.model.GuestProto.Guest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object institution_ = "";
      /**
       * <code>string institution = 2;</code>
       * @return The institution.
       */
      public java.lang.String getInstitution() {
        java.lang.Object ref = institution_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          institution_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string institution = 2;</code>
       * @return The bytes for institution.
       */
      public com.google.protobuf.ByteString
          getInstitutionBytes() {
        java.lang.Object ref = institution_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          institution_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string institution = 2;</code>
       * @param value The institution to set.
       * @return This builder for chaining.
       */
      public Builder setInstitution(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        institution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string institution = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstitution() {
        
        institution_ = getDefaultInstance().getInstitution();
        onChanged();
        return this;
      }
      /**
       * <code>string institution = 2;</code>
       * @param value The bytes for institution to set.
       * @return This builder for chaining.
       */
      public Builder setInstitutionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        institution_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 4;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:guestbook.Guest)
    }

    // @@protoc_insertion_point(class_scope:guestbook.Guest)
    private static final com.guestbookfe.model.GuestProto.Guest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guestbookfe.model.GuestProto.Guest();
    }

    public static com.guestbookfe.model.GuestProto.Guest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Guest>
        PARSER = new com.google.protobuf.AbstractParser<Guest>() {
      @java.lang.Override
      public Guest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Guest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Guest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Guest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.guestbookfe.model.GuestProto.Guest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GuestsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:guestbook.Guests)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    java.util.List<com.guestbookfe.model.GuestProto.Guest> 
        getGuestList();
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    com.guestbookfe.model.GuestProto.Guest getGuest(int index);
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    int getGuestCount();
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    java.util.List<? extends com.guestbookfe.model.GuestProto.GuestOrBuilder> 
        getGuestOrBuilderList();
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    com.guestbookfe.model.GuestProto.GuestOrBuilder getGuestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code guestbook.Guests}
   */
  public static final class Guests extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:guestbook.Guests)
      GuestsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Guests.newBuilder() to construct.
    private Guests(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Guests() {
      guest_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Guests();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Guests(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                guest_ = new java.util.ArrayList<com.guestbookfe.model.GuestProto.Guest>();
                mutable_bitField0_ |= 0x00000001;
              }
              guest_.add(
                  input.readMessage(com.guestbookfe.model.GuestProto.Guest.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          guest_ = java.util.Collections.unmodifiableList(guest_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guests_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guests_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guestbookfe.model.GuestProto.Guests.class, com.guestbookfe.model.GuestProto.Guests.Builder.class);
    }

    public static final int GUEST_FIELD_NUMBER = 1;
    private java.util.List<com.guestbookfe.model.GuestProto.Guest> guest_;
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.guestbookfe.model.GuestProto.Guest> getGuestList() {
      return guest_;
    }
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.guestbookfe.model.GuestProto.GuestOrBuilder> 
        getGuestOrBuilderList() {
      return guest_;
    }
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    @java.lang.Override
    public int getGuestCount() {
      return guest_.size();
    }
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    @java.lang.Override
    public com.guestbookfe.model.GuestProto.Guest getGuest(int index) {
      return guest_.get(index);
    }
    /**
     * <code>repeated .guestbook.Guest guest = 1;</code>
     */
    @java.lang.Override
    public com.guestbookfe.model.GuestProto.GuestOrBuilder getGuestOrBuilder(
        int index) {
      return guest_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < guest_.size(); i++) {
        output.writeMessage(1, guest_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < guest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, guest_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guestbookfe.model.GuestProto.Guests)) {
        return super.equals(obj);
      }
      com.guestbookfe.model.GuestProto.Guests other = (com.guestbookfe.model.GuestProto.Guests) obj;

      if (!getGuestList()
          .equals(other.getGuestList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGuestCount() > 0) {
        hash = (37 * hash) + GUEST_FIELD_NUMBER;
        hash = (53 * hash) + getGuestList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guestbookfe.model.GuestProto.Guests parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guestbookfe.model.GuestProto.Guests prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code guestbook.Guests}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:guestbook.Guests)
        com.guestbookfe.model.GuestProto.GuestsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guests_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guests_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guestbookfe.model.GuestProto.Guests.class, com.guestbookfe.model.GuestProto.Guests.Builder.class);
      }

      // Construct using com.guestbookfe.model.GuestProto.Guests.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGuestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (guestBuilder_ == null) {
          guest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          guestBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guestbookfe.model.GuestProto.internal_static_guestbook_Guests_descriptor;
      }

      @java.lang.Override
      public com.guestbookfe.model.GuestProto.Guests getDefaultInstanceForType() {
        return com.guestbookfe.model.GuestProto.Guests.getDefaultInstance();
      }

      @java.lang.Override
      public com.guestbookfe.model.GuestProto.Guests build() {
        com.guestbookfe.model.GuestProto.Guests result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.guestbookfe.model.GuestProto.Guests buildPartial() {
        com.guestbookfe.model.GuestProto.Guests result = new com.guestbookfe.model.GuestProto.Guests(this);
        int from_bitField0_ = bitField0_;
        if (guestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            guest_ = java.util.Collections.unmodifiableList(guest_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.guest_ = guest_;
        } else {
          result.guest_ = guestBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guestbookfe.model.GuestProto.Guests) {
          return mergeFrom((com.guestbookfe.model.GuestProto.Guests)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guestbookfe.model.GuestProto.Guests other) {
        if (other == com.guestbookfe.model.GuestProto.Guests.getDefaultInstance()) return this;
        if (guestBuilder_ == null) {
          if (!other.guest_.isEmpty()) {
            if (guest_.isEmpty()) {
              guest_ = other.guest_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGuestIsMutable();
              guest_.addAll(other.guest_);
            }
            onChanged();
          }
        } else {
          if (!other.guest_.isEmpty()) {
            if (guestBuilder_.isEmpty()) {
              guestBuilder_.dispose();
              guestBuilder_ = null;
              guest_ = other.guest_;
              bitField0_ = (bitField0_ & ~0x00000001);
              guestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGuestFieldBuilder() : null;
            } else {
              guestBuilder_.addAllMessages(other.guest_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guestbookfe.model.GuestProto.Guests parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guestbookfe.model.GuestProto.Guests) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.guestbookfe.model.GuestProto.Guest> guest_ =
        java.util.Collections.emptyList();
      private void ensureGuestIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          guest_ = new java.util.ArrayList<com.guestbookfe.model.GuestProto.Guest>(guest_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.guestbookfe.model.GuestProto.Guest, com.guestbookfe.model.GuestProto.Guest.Builder, com.guestbookfe.model.GuestProto.GuestOrBuilder> guestBuilder_;

      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public java.util.List<com.guestbookfe.model.GuestProto.Guest> getGuestList() {
        if (guestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(guest_);
        } else {
          return guestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public int getGuestCount() {
        if (guestBuilder_ == null) {
          return guest_.size();
        } else {
          return guestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public com.guestbookfe.model.GuestProto.Guest getGuest(int index) {
        if (guestBuilder_ == null) {
          return guest_.get(index);
        } else {
          return guestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder setGuest(
          int index, com.guestbookfe.model.GuestProto.Guest value) {
        if (guestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuestIsMutable();
          guest_.set(index, value);
          onChanged();
        } else {
          guestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder setGuest(
          int index, com.guestbookfe.model.GuestProto.Guest.Builder builderForValue) {
        if (guestBuilder_ == null) {
          ensureGuestIsMutable();
          guest_.set(index, builderForValue.build());
          onChanged();
        } else {
          guestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder addGuest(com.guestbookfe.model.GuestProto.Guest value) {
        if (guestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuestIsMutable();
          guest_.add(value);
          onChanged();
        } else {
          guestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder addGuest(
          int index, com.guestbookfe.model.GuestProto.Guest value) {
        if (guestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuestIsMutable();
          guest_.add(index, value);
          onChanged();
        } else {
          guestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder addGuest(
          com.guestbookfe.model.GuestProto.Guest.Builder builderForValue) {
        if (guestBuilder_ == null) {
          ensureGuestIsMutable();
          guest_.add(builderForValue.build());
          onChanged();
        } else {
          guestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder addGuest(
          int index, com.guestbookfe.model.GuestProto.Guest.Builder builderForValue) {
        if (guestBuilder_ == null) {
          ensureGuestIsMutable();
          guest_.add(index, builderForValue.build());
          onChanged();
        } else {
          guestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder addAllGuest(
          java.lang.Iterable<? extends com.guestbookfe.model.GuestProto.Guest> values) {
        if (guestBuilder_ == null) {
          ensureGuestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, guest_);
          onChanged();
        } else {
          guestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder clearGuest() {
        if (guestBuilder_ == null) {
          guest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          guestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public Builder removeGuest(int index) {
        if (guestBuilder_ == null) {
          ensureGuestIsMutable();
          guest_.remove(index);
          onChanged();
        } else {
          guestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public com.guestbookfe.model.GuestProto.Guest.Builder getGuestBuilder(
          int index) {
        return getGuestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public com.guestbookfe.model.GuestProto.GuestOrBuilder getGuestOrBuilder(
          int index) {
        if (guestBuilder_ == null) {
          return guest_.get(index);  } else {
          return guestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public java.util.List<? extends com.guestbookfe.model.GuestProto.GuestOrBuilder> 
           getGuestOrBuilderList() {
        if (guestBuilder_ != null) {
          return guestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(guest_);
        }
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public com.guestbookfe.model.GuestProto.Guest.Builder addGuestBuilder() {
        return getGuestFieldBuilder().addBuilder(
            com.guestbookfe.model.GuestProto.Guest.getDefaultInstance());
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public com.guestbookfe.model.GuestProto.Guest.Builder addGuestBuilder(
          int index) {
        return getGuestFieldBuilder().addBuilder(
            index, com.guestbookfe.model.GuestProto.Guest.getDefaultInstance());
      }
      /**
       * <code>repeated .guestbook.Guest guest = 1;</code>
       */
      public java.util.List<com.guestbookfe.model.GuestProto.Guest.Builder> 
           getGuestBuilderList() {
        return getGuestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.guestbookfe.model.GuestProto.Guest, com.guestbookfe.model.GuestProto.Guest.Builder, com.guestbookfe.model.GuestProto.GuestOrBuilder> 
          getGuestFieldBuilder() {
        if (guestBuilder_ == null) {
          guestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.guestbookfe.model.GuestProto.Guest, com.guestbookfe.model.GuestProto.Guest.Builder, com.guestbookfe.model.GuestProto.GuestOrBuilder>(
                  guest_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          guest_ = null;
        }
        return guestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:guestbook.Guests)
    }

    // @@protoc_insertion_point(class_scope:guestbook.Guests)
    private static final com.guestbookfe.model.GuestProto.Guests DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guestbookfe.model.GuestProto.Guests();
    }

    public static com.guestbookfe.model.GuestProto.Guests getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Guests>
        PARSER = new com.google.protobuf.AbstractParser<Guests>() {
      @java.lang.Override
      public Guests parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Guests(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Guests> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Guests> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.guestbookfe.model.GuestProto.Guests getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_guestbook_Guest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_guestbook_Guest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_guestbook_Guests_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_guestbook_Guests_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017guestbook.proto\022\tguestbook\"J\n\005Guest\022\014\n" +
      "\004name\030\001 \001(\t\022\023\n\013institution\030\002 \001(\t\022\r\n\005emai" +
      "l\030\003 \001(\t\022\017\n\007message\030\004 \001(\t\")\n\006Guests\022\037\n\005gu" +
      "est\030\001 \003(\0132\020.guestbook.GuestB#\n\025com.guest" +
      "bookfe.modelB\nGuestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_guestbook_Guest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_guestbook_Guest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_guestbook_Guest_descriptor,
        new java.lang.String[] { "Name", "Institution", "Email", "Message", });
    internal_static_guestbook_Guests_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_guestbook_Guests_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_guestbook_Guests_descriptor,
        new java.lang.String[] { "Guest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
